# derivations for node.js-based applications in NixOS are supposed to be generated by node2nix
{ stdenv, pkgs, fetchurl }:
let
  nodeDependencies = ( pkgs.callPackage ./mempool-backend.nix {}).shell.nodeDependencies;
in
stdenv.mkDerivation {
  name = "mempool";

  src = fetchurl {
    url = "https://github.com/mempool/mempool/archive/refs/tags/v2.2.0.tar.gz";
    sha256 = "1gccza1s28ja78iyqv5h22ix5w21acbvffahsb5ifn27q4bq8mk3";
  };
  buildInputs = with pkgs;
  [ nodejs
  ];
  preConfigure = "cd backend";
  buildPhase = ''
    export PATH="${nodeDependencies}/bin:$PATH"
    cp -r ${nodeDependencies}/lib/node_modules ./node_modules
    echo "going to run npm now"
    npm install
    npm run build
  '';
}
